# Generated by Django 3.1.6 on 2021-02-05 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Webdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webdata_name', models.CharField(max_length=100)),
                ('webdata_date', models.DateField()),
            ],
        ),
    ]
