# Generated by Django 3.1.6 on 2021-02-05 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frequency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webdata',
            name='webdata_list',
            field=models.TextField(null=True),
        ),
    ]
