# Generated by Django 3.1.6 on 2021-02-05 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frequency', '0002_webdata_webdata_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webdata',
            name='webdata_date',
        ),
    ]
